# Generated by Django 2.1.5 on 2019-02-14 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('guest_name', models.CharField(max_length=300)),
                ('function_name', models.CharField(max_length=400)),
                ('max_rsvp', models.IntegerField()),
                ('done_rsvp', models.IntegerField()),
                ('digest', models.CharField(max_length=35)),
                ('url', models.CharField(max_length=250)),
            ],
        ),
    ]
