# Generated by Django 2.1.5 on 2019-02-14 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0002_auto_20190214_0841'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='qrcode',
            field=models.ImageField(default='', upload_to='rsvp'),
        ),
    ]
