# Generated by Django 2.2.3 on 2019-07-21 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0006_auto_20190721_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='function_name',
        ),
    ]
